# Generated by Django 4.2 on 2024-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_member_introduction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
